### ISSUE TITLE
Support for additional characters in variables

### ISSUE THREAD

**Issue by CodeMaven** [scijava/parsington#10]
I require 'special' variables in a project that I am working on. Specifically, these are system provided environment variables that will be handled different from regular variables. To do this, I would like to allow either '$' or '_' as prefixes on an identifier in ExpressionParser.java parseIdentifier. For example:

"CodeMaven" == $LOGIN
"Production" == $ENV && testEnv != $ENV

Currently parseIdentifier only allows variables to begin with Character.isUnicodeIdentifierStart() values. If I were to submit a pull request to allow _ and $ as options too, would it be accepted?
Thanks,
Troy

**Comment by ctrueden** [comment]
@CodeMaven Very sorry for the lack of response till now.

It looks like the `Character.isUnicodeIdentifier*` logic is confined to the `public int parseIdentifier()` method. Did you try extending the `ExpressionParser` class to override that method with the behavior you need? Do you think that would be sufficient for your need?

**Comment by CodeMaven** [comment]
Hi, I was thinking of implementing $ as a unary prefix as you mention. I did come up with a workaround for my purposes by simply reserving certain variable names... but this is not ideal. I plan to revisit it.

**Comment by kkieffer** [comment]
FYI, I had the same issue.  I wanted to use $var as special variables.  The call `public int parseIdentifier() `can't be overridden, its in a private nested class.  Surrounding it in { } was my workaround as well.

**Comment by ctrueden** [comment]
@kkieffer wrote:
> The call `public int parseIdentifier()` can't be overridden, its in a private nested class.

Ahh, yeah, thanks for pointing that out!

Is there anything that you would want changed in Parsington to better accommodate your needs? New standard operators, for example? Or are you happy with how it currently is now that you have a working solution?

**Comment by kkieffer** [comment]
So far, so good.  Really glad I found this library.  It's working really well.

**Comment by ctrueden** [comment]
I added an example to the [TestExamples](src/test/java/org/scijava/parsington/TestExamples) called `dollarSignPrefixedVariablesAreSpecial` which showcases how to add a high-priority unary `$` operator, and then extend the `DefaultTreeEvaluator` to evaluate it as an environment variable from the system.

Furthermore, with the latest code on the main branch, the `ParseOperation` class is now a public outer class, which can be overridden to fine-tune the behavior of the various parsing steps. But I don't think you need that for this `$`-prefixed special variables use case.

@CodeMaven @kkieffer Hopefully this meets your needs, but please reopen if it's still not sufficient or elegant enough! :smile:
