### ISSUE TITLE
Evaluating an expression with a plain variable name does not return its value, but its name

### ISSUE THREAD

**Issue by davidlinner** [scijava/parsington#18]
I've added a simple test case for Junit5 and Hamcrest below to illustrate the problem. The bug was found in version 2.1.0 and 3.0.0 of the library.

**Expected**: Variable is evaluated to its value.

**Actual**: Variable name is returned.

    package org.any;
    
    import org.junit.jupiter.api.Test;
    import org.scijava.parsington.Variable;
    import org.scijava.parsington.eval.DefaultTreeEvaluator;
    
    import static org.hamcrest.MatcherAssert.assertThat;
    import static org.hamcrest.Matchers.*;
    
    public class ParsingtonTest {
    
        @Test // fails
        void testPlainVariableEvaluation(){
            DefaultTreeEvaluator evaluator = new DefaultTreeEvaluator();
            evaluator.set(new Variable("x"), 10);
            assertThat(evaluator.evaluate("x"), is(10));
        }
    
        @Test // passes
        void testVariableInSimpleExpression(){
            DefaultTreeEvaluator evaluator = new DefaultTreeEvaluator();
            evaluator.set(new Variable("x"), 10);
            assertThat(evaluator.evaluate("x+0"), is(10));
        }
    
    }

Great library! Thank you for sharing. I was searching long time for a well maintained, simple evaluator for math expressions on the JVM.

**Comment by ctrueden** [comment]
@davidlinner Glad you find the library useful, and thanks for the clear report. Your post prompted me to migrate Parsington to JUnit 5 (9743dbaaee3a352d8de14ab71e0af60fd1d01047), so thanks for that. :smile:

As for the behavior where the evaluator returns a `Variable` object: it's intended. The expression `x` really _is_ that variable, not only its value. To get the value, you can call the `Evaluator#value(Object)` method, which is a convenience method for unwrapping `Variable` objects. If you modify `testPlainVariableEvaluation` to be:
```java
DefaultTreeEvaluator evaluator = new DefaultTreeEvaluator();
evaluator.set(new Variable("x"), 10);
Object result = evaluator.evaluate("x");
assertThat(evaluator.value(result), is(10));
```
then the test should pass.

**Comment by davidlinner** [comment]
@ctrueden Thank you for clarification. I missed `Evaluator.value` in the documentation. My test case is now indeed working. Just for curiosity, why isn't `evaluate` always returning a value?

**Comment by ctrueden** [comment]
> Just for curiosity, why isn't `evaluate` always returning a value?

It's a good question. By the evaluation algorithm, the end result when evaluating an expression like `x` or `x = 5` or `x = y = 5` is definitely the variable `x`. But we could change the `evaluate` methods themselves to always unwrap the end result. I guess my intuition was just that the caller might care that the result of the evaluation was a variable rather than only its value, and that if all they wanted was its value, they would unwrap it. But I don't have a concrete use case where the caller would need to know that the evaluation result was a variable. It just felt wrong to me to throw away that information.

**Comment by davidlinner** [comment]
I understand, thank you for explaining. One could argue that `x` as opposed to `x=1` is an expression and not a statement. For this reason a value could be returned when there is not assignment. The python interpreter behaves this way. Javascript interpreters evaluate assignments as expressions, for example `(x = 5)==5` is evaluated to `true`. I guess it's your choice. I know what to do now. Thanks again.
