### ISSUE TITLE
Recognize variable names with complexity

### ISSUE THREAD

**Issue by ocaspari** [scijava/parsington#19]
Hello, thanks for this parser. I have an issue with the recognition of variables. Indeed, their names can be everything like "var.xxx". However, because of the 'dot', it is not well parsed. 
One of my solution was to replace the dot, however, it is just for this char. I was wondering if it was possible to evoluate the parser to have a way to indicate that a variable is a variable (like [var.xxx] or something like that).
Thanks.

**Comment by ctrueden** [comment]
@ocaspari I can think of two ways to deal with syntax like `var.xxx`:

1. **Adjust the parser** to allow dots inside literals.
2. **Adjust the evaluator** to let the dot operator join two variables into a single one.

I added an example of each to the `TestExamples`; see dbe5145f1e23464b07704aa4e94e54eb5bc02466.

To make (1) easier to achieve, I also added a couple of new protected methods to the `ParseOperation` base class, so that you can override which characters are allowed for starting literals or continuing literals in a more targeted way; see d736137649718fc8e3f72a90e398de078432ca6e.

Let me know if you need any further guidance with it!

**Comment by ocaspari** [comment]
Thanks for the advises and the tests. Thats very kind. 
I think nonetheless that I face a more difficult aspect. Because the separated dot variable were juste an exemple. In fact, I can have a string with anything in it. To recognize that it is a variable, I try to surround its name by a personal pattern like variableName = "[this is my variable aa.bb + cc.dd]"  and replace each operator with a specified caracter.
But maybe it is not possible with the current structure to manage this aspect.

**Comment by ctrueden** [comment]
@ocaspari Sure, one common way of handling expressions like that is with `${` to start and `}` to end. Or just `{` and `}` like for example Python f-strings. To accomplish that in Parsington, you just need to override the `parseIdentifier` method to detect it.

I would write you an example, but I am still not 100% clear yet: you want the string `[this is my variable aa.bb + cc.dd]` to be parsed into a single `Variable` token that is literally named that? And you do _not_ want to do any parsing inside the square brackets? Is that correct?

**Comment by ocaspari** [comment]
@ctrueden. Thank you for you fast  aswer. "[this is my variable aa.bb + cc.dd] to be parses into a singled Variable token that is literally named that" : this is exactly that I want.
"You do not want to do any parsing inside the square brackets" -> exactly. The idea is to let a user declare a variable associated to an operation. So if he wants to declare the variable "3+4" associated to the operation 3+4 then use this variable in another operation, I'd like to let him this possibility. Of course, to identify that "3+4" is a variable, it should be surrounded by a specific character (the square brackets). If you say that there is a solution, this is perfect !!! 
Thank you.

**Comment by ctrueden** [comment]
@ocaspari I pushed an example: 924c21552eefe961351e0d96c2674d73b5162da1. I hope it helps!

**Comment by ocaspari** [comment]
I just did few tests with your example and it works perfectly so far !! Thank you very much for your help and for this project !
