### ISSUE TITLE
Support scientific notation

### ISSUE THREAD

**Issue by cath34** [scijava/parsington#8]
Hi,
I am currently working on a research project and we are using parsington to evaluate mathematical expressions.  

It seems that parsington does not support the scientific notation.  For example, if I want to parse the infix expression (6E-4 + x), it throws an IllegalArgumentException (Invalid character at index 1). Do you plan to support scientific notation one day?

**Comment by ctrueden** [comment]
@cath34 Thanks for the report! Parsington does support scientific notation, but there was a bug in the numeric literal parsing with negative exponents. E.g. 6e4 worked, but 6e-4 gave an invalid character exception as you noted. I fixed the bug (see 89b723189af2ae7fbdca76ade4e2bb70df69127a) and [released version 1.0.2](https://oss.sonatype.org/#nexus-search;gav~org.scijava~parsington~1.0.2~~).

**Comment by cath34** [comment]
Awesome! Thank you :)
